#!/usr/bin/bash

# Save the terminal's screen prior to launching app
echo -en '\e[?1049h'
shopt -s extglob
#################################################################################
#				      VARS					#
#################################################################################
declare -n breg=BASH_REMATCH

Black='\e[30m'
R='\e[31m'
G='\e[32m'
Y='\e[33m'
B='\e[34m'
M='\e[35m'
C='\e[36m'
W='\e[37m'
default='\e[39m'
reset='\e[0m'

Blackbg='\e[40m'
Rbg='\e[41m'
Gbg='\e[42m'
Ybg='\e[43m'
Bbg='\e[44m'
Mbg='\e[45m'
Cbg='\e[46m'
Wbg='\e[47m'
defaultbg='\e[49m'

BrBlack='\e[90m'
BrR='\e[91m'
BrY='\e[92m'
BrG='\e[93m'
BrB='\e[94m'
BrM='\e[95m'
BrC='\e[96m'
BrW='\e[97m'

BrBlackbg='\e[100m'
BrRbg='\e[101m'
BrGbg='\e[102m'
BrYbg='\e[103m'
BrBbg='\e[104m'
BrMbg='\e[105m'
BrCbg='\e[106m'
BrWbg='\e[107m'

Bold='\e[1m'
UL='\e[4m'

splash=(
"${R}██████╗ ${G} █████╗ ${Y} ██████  ${B}██   ██╗ ${M}██   ██╗ ${R} █████╗ ${G}██████ ${Y}██╗   "
"${R}██║ ██║ ${G}██║  ██ ${Y}██╔═══╝  ${B}██   ██║ ${M}███ ███║ ${R}██║  ██ ${G}  ██╔╝ ${Y}██║   "
"${R}█████╔╝ ${G}███████ ${Y}███████╗ ${B}███████║ ${M}██║█ ██║ ${R}███████ ${G}  ██║  ${Y}██║   "
"${R}██║ ██╗ ${G}██║  ██ ${Y}     ██║ ${B}██║  ██║ ${M}██║  ██║ ${R}██║  ██ ${G}  ██╚╗ ${Y}██╚══╗"
"${R}██████╝ ${G}██╝  ██ ${Y}██████═╝ ${B}██╝  ██╝ ${M}██╝  ██╝ ${R}██╝  ██ ${G}██████ ${Y}██████")

splashlen=$(echo "${splash[0]}"|grep -m 1 '^..*'|sed -e "s/\\\e\[[0-9;]*[a-zA-Z]//g; s/$'\e'//g"|tr -d '\n'|wc -m)
splashcols=${#splash[@]}

linestart=10
linepos=10
message_line_pos=0

# Pipes
sendssl="/var/tmp/sendssl.log"
readssl="/var/tmp/readssl.log"

A="A"

declare unread_str bottom_text mode marked_str
declare -i lines columns margin_top margin_bottom unreadcount first_linepos last_linepos\
	linepos prevlinepos bottomline termcenter splashcenter splashstart splashcols\
	state max_shown max_inbox_line index_at_cursor prev_index inbox_newest_id\
	inboxcount
declare -a unread_msg_ids open_message marked_messages from_arr subject_arr unread_header_arr\
	inbox_header_arr inbox_header_arr inbox_msg_ids
declare -A folder unread_range open_message_range inbox_range

##################################################################################
#			   CURSOR AND SCREEN CONTROLS				 #
##################################################################################

function save_screen() {
    echo -en '\e[?1049h'
}

function restore_screen() {
    echo -en '\e[?1049l'
}

function forward_line () {
    if (( message_line_pos == lines && open_message_range[bottom] >= lines - 1)); then
	redraw_bottom_message_line --message
    else
	echo -en '\e[1E'
	(( message_line_pos++ ))
    fi
}

function backward_line () {
    if (( message_line_pos == 0 && open_message_range[top] > 0 )); then
	redraw_top_message_line --message
    else
	echo -en '\e[1F'
	(( message_line_pos-- ))
    fi
}

function redraw_top_message_line() {
    # Draw a blank line at line 1
    echo -en '\e[1T'
    set_cursor 0 0
    if [[ "$1" == "--message" ]]; then
	hide_cursor
	(( open_message_range[top]-- ))
	(( open_message_range[bottom]-- ))
	echo -en "${open_message[${open_message_range[top]}]}"
	set_cursor 0 0
	show_cursor
    fi
}

function redraw_bottom_message_line() {
    # Draw a blank line at bottom line
	if [[ "$1" == "--message" ]]; then
	    if (( open_message_range[bottom] < ${#open_message[@]} - 1 )); then
		echo -en '\e[1S'
		set_cursor $lines 0
		hide_cursor
		(( open_message_range[top]++ ))
		(( open_message_range[bottom]++ ))
		echo -en "${open_message[${open_message_range[bottom]}]}"
		set_cursor $lines 0
		show_cursor
	    fi
	fi
}

function draw_previous_page() {
    # If line 1 is > message index 0, draw previous n $lines on screen
    # If message index 0 is reached, stop there, print on line 1 through n $lines
    open_message_range[top]=$(( open_message_range[top] - lines ))
    open_message_range[bottom]=$(( open_message_range[top] + lines - 1 ))
    if (( open_message_range[top] >= 0 )); then
	# Define index 1 first to reference current index 0 as start point
	hide_cursor
	clear
	set_cursor 0 0
	for (( i=0;i<lines;i++ )); do
	    set_cursor $i 0
	    echo -en "${open_message[open_message_range[top]+i]}"
	done
	set_cursor 0 0
	message_line_pos=1
	show_cursor
    else
	hide_cursor
	clear
	for (( i=0;i<lines;i++ )); do
	    set_cursor $i 0
	    echo -en "${open_message[i]}"
	done
	set_cursor 0 0
	show_cursor
	open_message_range[top]=0
	open_message_range[bottom]=$(( open_message_range[top] + lines - 1))
	message_line_pos=1
    fi
}

function draw_next_page() {
    # If there are >=n $lines ahead in message indexes, print n lines
    # Else, print any remainder < n $lines
    # If end of message visible, do nothing
    message_remaining_lines=$(( ${#open_message[@]} - open_message_range[bottom] + 1 ))
    open_message_range[top]=$(( open_message_range[bottom] + 1 ))
    if (( message_remaining_lines >= lines )); then
	open_message_range[bottom]=$(( open_message_range[top] + lines - 1 ))
	hide_cursor
	clear
	set_cursor 0 0
	for (( i=0;i<lines;i++ )); do
	    set_cursor $i 0
	    echo -en "${open_message[open_message_range[top]+i]}"
	done
	set_cursor 0 0
	message_line_pos=1
	show_cursor
    elif (( message_remaining_lines > 0 )); then
	open_message_range[bottom]=$(( open_message_range[top] + message_remaining_lines - 1 ))
	hide_cursor
	clear
	for (( i=0;i<message_remaining_lines;i++ )); do
	    set_cursor $i 0
	    echo -en "${open_message[open_message_range[top]+i]}"
	done
	set_cursor 0 0
	show_cursor
	message_line_pos=1
    fi
}

function forward_column () {
    echo -en '\e[1C'
}

function backward_column () {
    echo -en '\e[1D'
}

function set_cursor() {
    if (( $1 > lines )); then
	echo "Invalid line"
	return
    elif (( $2 > columns )); then
	echo "Invalid column"
	return
    else
	echo -en '\e['"$1"';'"$2"'H'
    fi
}

function hide_cursor() {
    echo -en '\e[?25l'
}

function show_cursor() {
    echo -en '\e[?25h'
}

function hide_prompt() {
    echo -en '\e[8m'
}

function show_prompt() {
    echo -en '\e[28m'
}

function hide_mode() {
    echo -en '\e[8m\e[?25l'
}

function hide_mode_off() {
    echo -en '\e[28m\e[?25h'
}

function reset_colors() {
    echo -en '\e[0m'
}

function set_scroll_area() {
    # $1 top. $2 bottom.
    echo -en "\e[$1;$2r"
}

function reset_scroll_area() {
    echo -en '\e[;r'
}

function set_top_margin() {
    set_cursor 1 1; reset_colors
    echo -e "$BrBlackbg  [Unread]$defaultbg  [Inbox]"
}

function update_top_margin() {
    set_cursor 1 1; reset_colors
    if [[ "$1" == "--inbox" ]]; then
	echo -e "$defaultbg  [Unread]$BrBlackbg  [Inbox]"
    elif [[ "$1" == "--unread" ]]; then
	echo -e "$BrBlackbg  [Unread]$defaultbg  [Inbox]"
    fi
    set_cursor $linepos 1; reset_colors
}

function erase_line() {
    echo -en '\e[2K'
}

function erase_cursor_to_line_end() {
    echo -en '\e[0K'
}

function erase_cursor_to_screen_end() {
    echo -en '\e[0J'
}

function erase_backwards() {
    echo -en '\e[1K'
}

function echo_list() {
    local -n arr=$1
    for (( i=0; i<${arr[@]}; i++ )); do
	echo "${arr[${i}]}"
    done
}

function get_index_n() {
    # $1: Array
    # $2: String to match
    local -n arr=$1
    for (( i=0;i<${#arr[@]};i++ )); do
	if [[ "${arr[i]}" == "$2" ]]; then
	    echo "$i"
	    break
	fi
    done
}

function clearfifo() {
    while read -r -t 0.5 line; do
	continue
    done <&$readfd
}

function get_folders() {
    # Store the server's folder names in an associative array for
    # easy access when needed
    [[ "$email" =~ "gmail.com" ]] && folder[archived]="\"[Gmail]/All Mail\""
    echo "$A LIST \"\" \"*\"" >&$sendfd # Response is a list of all folders
    while read -r line; do
	[[ "$line" =~ " OK " ]] && break
	[[ "$line" =~ " BAD "|" NO " ]] && draw_popup --warn "Failed to get folders\nInbox/Unread available" && break
	if [[ "$line" =~ \"[Aa]rchive\"|\"[Aa]rchived\" ]]; then
	    folder[archived]="${breg//[$'\n'|$'\r']/}"
	fi
	if [[ "$line" =~ \\Trash[^\"]*\"[^\"]*\"[^\"]*(\".*\") ]]; then
	    folder[trash]="${breg[1]//[$'\n'|$'\r']/}"
	fi
	if [[ "$line" =~ \\Junk[^\"]*\"[^\"]*\"[^\"]*(\".*\")|(\"[Jj]unk\") ]]; then
	    if [[ -n "${breg[1]}" ]]; then
		folder[junk]="${breg[1]//[$'\n'|$'\r']/}"
	    elif [[ -n "${breg[2]}" ]]; then
		folder[junk]="${breg[2]//[$'\n'|$'\r']/}"
	    fi
	fi
    done <&$readfd
}
	   
function get_unread_messages() {
    # Send request to server for list of unread message IDs
    # Store in array $unread
    # 0 args check is the initial call only
    if (( $# == 0 )); then
	echo "$A SELECT INBOX" >&$sendfd
	while read -r line; do
	    if [[ "$line" =~ "$A OK " ]]; then
		hide_mode_off
		echo "Inbox selected"
		splash_forward_line
		hide_mode
		break
	    elif [[ "$line" =~ ([0-9]{1,})" "EXISTS|([0-9]{1,})" "exists ]]; then
		inbox_newest_id="${breg[1]}"
	    elif [[ "$line" =~ " BAD "|" NO " ]]; then
		draw_popup --error "Failed to open inbox"
		exit
	    fi
	done <&$readfd
    fi
    clearfifo
    echo "$A SEARCH UNSEEN" >&$sendfd
    while read -r line; do
	if [[ "$line" =~ " OK " ]]; then
	    break
	fi
	if [[ "$line" =~ " BAD "|" NO " ]]; then
	    echo "Failed unread search"
	    sleep 3s
	    exit
	fi
	if [[ "$line" =~ SEARCH" "([0-9].*) ]]; then
	    id_str="${breg[1]//$'\r'/}"
	    IFS=" "
	    unread_msg_ids+=($(echo -n "${id_str//[$'\r'|$'\n']/}"))
	    unset IFS
	    unread_str="${id_str// /,}"
	    unreadcount=${#unread_msg_ids[@]}
	    # Store the terminal line numbers
	    first_linepos=2
	    # The final line position of index unread_header_arr[-1]
	    last_linepos=$(( unreadcount * 2 ))
	    linepos=2
	    prevlinepos=0
	fi
    done <&$readfd
}

function reset_indexes() {
    # Unset all indexes of any passed array names
    # Args should be strings not prefixed with "$"
    for i in $(seq 1 $#); do
	# Expand $i with ${!i} to get the string from $1,2,3...
	local -n arg_arr=${!i}
	unset "arg_arr[@]"
    done
}

function fetch_header_field() {
    clearfifo
    echo "$A FETCH $1 body.peek[header.fields (from subject)]" >&$sendfd
    i=0
    while read -rs line; do
	if [[ "$line" =~ " OK " ]]; then break; fi
	if [[ "$line" =~ " BAD "|" NO " ]]; then draw_popup --error "Failed to retrieve headers"; fi
	# Bytes are found on first line in "{0-9}"
	if [[ "$line" =~ \{[0-9]+\} ]]; then
	    local -i bytes
	    bytes=$(echo "${breg//["{"|"}"|$'\n']/}")
	    if (( bytes > 0 )); then
		read -rN $bytes body <&$readfd
		regex1="[Ff]rom: (.*)[Ss]ubject"
		regex2="[Ff]rom: (.*)"
		# From and Subject can come in random order, so check both possibilities
		if [[ "$body" =~ $regex1 || "$body" =~ $regex2 ]]; then
		    regval="${breg[1]//[$'\n'|\"]/}"
		    regex="^[[:space:]]?([^\<]{1,})"
		    if [[ "$regval" =~ $regex ]]; then
			from_arr[i]="${breg[1]//[$'\r'|$'\n']/}"
		    else
			from_arr[i]="${regval//[$'\r'|$'\n'|<|>]/}"
		    fi
		    regex1="[Ss]ubject: (.*)[Ff]rom"
		    regex2="[Ss]ubject: (.*)"
		    if [[ "$body" =~ $regex1 || "$body" =~ $regex2 ]]; then
			subject_arr[i]="${breg[1]//[$'\n'\"$'\r']/}"
		    fi
		    (( i++ ))
		fi
	    fi
	fi
    done <&$readfd
}

function parse_headers() {
    if [[ "$1" == "--unread" ]]; then
	local -i count=$unreadcount
    elif [[ "$1" == "--inbox" ]]; then
	local -i count=$inboxcount
    fi
    for (( i=0;i<count;i++ )); do
	if [[ "${from_arr[i]}" =~ \?[Bb]\? ]]; then
	    from_arr[i]=$(decode_b64 from_arr $i);
	fi
	if [[ "${from_arr[i]}" =~ \?[Qq]\? ]]; then
	    from_arr[i]=$(decode_qp --header "${from_arr[i]}");
	fi
	if [[ "${subject_arr[i]}" =~ \?[Bb]\? ]]; then
	    subject_arr[i]=$(decode_b64 subject_arr $i);
	fi
	if [[ "${subject_arr[i]}" =~ \?[Qq]\? ]]; then
	    subject_arr[i]=$(decode_qp --header "${subject_arr[i]}");
	fi
    done
}

function combine_headers() {
    # After parsing, join $from_arr and $subject_arr into one array ($unread_header_arr)
    # Alternating indexes. (Ex: 0 is From, 1 is Subject, 2 is From, 3 is Subject)
    if (( ${#from_arr[@]} == ${#subject_arr[@]} )); then
	local -i indexes=$(( ${#from_arr[@]} + ${#subject_arr[@]} ))
	local -n arr=$2
	for (( i=0;i<indexes;i+=2 )); do
	    arr[i]="${from_arr[-1]}"
	    unset from_arr[-1]
	    arr[i+1]="${subject_arr[-1]}"
	    unset subject_arr[-1]
	done
    fi
}



function draw_popup() {
    # Args: flags precede strings
    # --[warn|error] --[reload] "[text]"
    if [[ "$1" =~ \".*\" && "$2" =~ "--.*" ]]; then echo "Invalid format"; sleep 1.5s; return; fi
    args=("$@")
    local -i longest_line longest_line_center box_rows box_columns box_center\
	  tty_start_col tty_start_line
    local warn_colors error_colors default_colors colors
    warn_colors="$Ybg$Black$Bold"
    error_colors="$Rbg$Black$Bold"
    default_colors="$Gbg$Black$Bold"

    case "$args" in
	*"--error"*) colors="$error_colors";;
	*"--warn"*) colors="$warn_colors";;
	*) colors="$default_colors";;
    esac

    IFS=$'\n'
    local -a message=($(echo -e "${!#}")) # If multiline, store lines in indexes
    unset IFS
    # Find longest line from message
    longest_line=${#message[0]}
    for (( i=0;i<${#message[@]};i++ )); do
	if (( longest_line <= ${#message[i]} )); then
	    longest_line=${#message[i]}
	fi
    done
    longest_line_center=$(( longest_line / 2 ))
    box_columns=$(( longest_line + 4 )) # Add 2 for border, 2 for whitespace on ends
    box_rows=$(( 2 + ${#message[@]} ))
    box_center=$(( box_columns / 2 ))
    tty_start_col=$(( columns / 2 - box_center ))
    tty_start_line=$(( lines / 2 - box_rows ))
    set_cursor $tty_start_line $tty_start_col
    reset_colors
    echo -en "$colors"
    for (( i=0;i<box_rows;i++ )); do
	line_len=${#message[i-1]}
	line_center=$(( line_len / 2 ))
	text_start_col=$(( longest_line_center - line_center + (line_len % 2) ))
	text_end_col=$(( text_start_col + line_len ))
	# Top Row
	if (( i == 0 )); then
	    echo -n "╔"
	    for (( j=0;j<box_columns-2;j++ )); do echo -n "═"; done
	    echo -n "╗"
	fi
	# Inner Rows
	if (( i != 0 && i != box_rows-1 )); then
	    echo -n "║"
	    for (( j=0;j<text_start_col;j++ )); do
		echo -n " "
	    done
	    echo -n "${message[i-1]}"
	    for (( j=0;j<box_columns-2-text_end_col;j++ )); do echo -n " "; done
	    echo -n "║"
	fi
	# Bottom Row
	if (( i == box_rows-1 )); then
	    echo -n "╚"
	    for (( j=0;j<box_columns-2;j++ )); do echo -n "═"; done
	    echo -n "╝"
	fi
	(( tty_start_line++ ))
	set_cursor $tty_start_line $tty_start_col
    done
    if [[ "${args[@]:1}" =~ "--restore-unread" ]]; then
	# Any keypress will close or 1.5s timeout
	read -rsn 1 -t 1.5
	draw_inbox --unread --restore; highlight --unread
    fi
    reset_colors
}

function draw_inbox() {
    # Either 0 args, or flag "--unread"
    # Clear the terminal
    clear
    hide_cursor
    set_scroll_area 2 36
    update_top_margin "$1"
    if [[ "$1" == "--unread" ]]; then
	local -n arr_range=unread_range
	local -n header_arr=unread_header_arr
	local -n ids_arr=unread_msg_ids
    elif [[ "$1" == "--inbox" ]]; then
	local -n arr_range=inbox_range
	local -n header_arr=inbox_header_arr
	local -n ids_arr=inbox_msg_ids
    fi

    local -i count=${#header_arr[@]}

    if [[ "$2" == "--restore" ]]; then
	local -i arr_index
	set_cursor $first_linepos 1
	for (( i=arr_range[top];i<arr_range[bottom]+2;i+=2 )); do
	    reset_colors
	    arr_index=$(rel_msg_index $i)
	    if [[ "${marked_messages[@]}" =~ "${ids_arr[arr_index]}" ]]; then
		echo -e "$W*$R${header_arr[i]}"; reset_colors
		echo -e " $Y${header_arr[i+1]}";
	    else
		echo -e " $R${header_arr[i]}"; reset_colors
		echo -e " $Y${header_arr[i+1]}"
	    fi
	done
	set_cursor $linepos 1
	if [[ -n "$bottom_text" ]]; then
	    set_bottom_bar $1
	fi
	return
    fi
	
    arr_range[top]=0
    for (( i=arr_range[top]; i<count; i+=2 )); do
	reset_colors
	echo -e " $R${header_arr[i]}"
	reset_colors
	if (( i+1 == count )); then
	    echo -en " $Y${header_arr[i+1]}"
	else
	    echo -e " $Y${header_arr[i+1]}"
	fi
    done
    arr_range[bottom]=$(( i - 2 ))
    index_at_cursor=0
    prev_index=0
    linepos=2
    prevlinepos=0
    set_cursor $linepos 1

    if [[ -n "$bottom_text" ]]; then
	set_bottom_bar $1
    fi
}

function switch_to_inbox() {
    update_top_margin --inbox
    # Retrieve a full page newest->oldest messages from the inbox
    local msg_range
    local -i inbox_id_limit=$(( inbox_newest_id - max_shown ))
    inboxcount=$(( inbox_newest_id - inbox_id_limit ))

    # Comma separated IDs, just like unread
    for (( i=inbox_newest_id;i>inbox_id_limit;i-- )); do
	if (( i-1 == inbox_id_limit )); then
	    msg_range+="$i"
	else
	    msg_range+="$i,"
	fi
    done

    # Also store these IDs in $inbox_msg_ids
    IFS=','
    ids_high_low=($(echo "$msg_range"))
    unset IFS
    # Reverse the order. This is done to match the expected ordering
    # used in combine_headers()
    for (( i=0;i<${#ids_high_low[@]};i++ )); do
	inbox_msg_ids[i]="${ids_high_low[-1-i]}"
    done
    draw_popup "Loading inbox"
    if (( ${#inbox_header_arr[@]} == 0 )); then
	fetch_header_field "$msg_range"
	parse_headers --inbox
	combine_headers --inbox inbox_header_arr
	clearfifo
	hide_mode_off
    fi
    # Update $last_linepos to reflect $inboxcount
    last_linepos=$(( inboxcount * 2 ))
    draw_inbox --inbox
    set_bottom_bar --inbox
    highlight --inbox
    inbox_nav_mode
}

function refresh_unread() {
    draw_popup "Reloading Unread"
    clearfifo
    reset_indexes marked_messages unread_msg_ids from_arr subject_arr unread_header_arr
    reset_colors
    get_unread_messages --reload
    fetch_header_field "$unread_str"
    parse_headers --unread
    combine_headers --unread unread_header_arr
    clearfifo
    hide_mode_off
    draw_inbox --unread
    set_bottom_bar --unread
    highlight --unread
}

# Relevant index of message
# $1: Either $prevlinepos or $linepos
function rel_msg_index() {
    local -i selected_line=$1
    echo -n $(( (last_linepos - $1) / 2 - 1 ))
}

function rel_header_index() {
    # $1 either prev_index or index_at_cursor
    echo -n $(( $1 / 2 ))
}

# To print the visibly highlighted index
function bottom_msg_at_cursor() {
    if [[ "$1" == "--unread" ]]; then
	local -n arr_range=unread_range
    elif [[ "$1" == "--inbox" ]]; then
	local -n arr_range=inbox_range
    fi
    echo $(( (arr_range[top] + linepos) / 2 ))
}

function set_bottom_bar() {
    [[ "$1" == "--unread" ]] && bottom_text="($(bottom_msg_at_cursor $1)/$unreadcount)"
    [[ "$1" == "--inbox" ]] && bottom_text="($(bottom_msg_at_cursor $1)/$inboxcount)"
    bottom_unused_cols=$(( columns - ${#bottom_text} - 1 ))
    set_cursor $bottomline 1
    erase_line
    echo -en "$Rbg$Black$Bold $bottom_text"
    for (( i=0; i<bottom_unused_cols; i++ )); do
	echo -n " "
    done
    set_cursor $linepos 0
}

function update_bottom_bar() {
    [[ "$1" == "--unread" ]] && local -i count=$unreadcount && bottom_text="($(bottom_msg_at_cursor $1)/$count)"
    [[ "$1" == "--inbox" ]] && local -i count=$inboxcount && bottom_text="($(bottom_msg_at_cursor $1)/$count)"
    if (( count > 1 )); then
	reset_colors
	hide_cursor
	local -i bottom_text_len=${#bottom_text}
	set_cursor $bottomline 1
	local -i bottom_text_diff=$(( columns - ${#bottom_text} - 1 ))
	if (( bottom_text_diff > 0 )); then
	    for (( i=0; i<bottom_text_diff; i++ )); do
		bottom_text+=" "
	    done
	fi
	echo -en "$Rbg$Black$Bold $bottom_text"
	reset_colors
	set_cursor $linepos 0
    fi
}

function highlight() {
    local -i prev_arr_index=$(rel_msg_index $prevlinepos)
    local -i arr_index=$(rel_msg_index $linepos)
    if [[ "$1" == "--unread" ]]; then
	local -n header_arr=unread_header_arr
	local -n id_arr=unread_msg_ids
	local -n arr_range=unread_range
    elif [[ "$1" == "--inbox" ]]; then
	local -n header_arr=inbox_header_arr
	local -n id_arr=inbox_msg_ids
	local -n arr_range=inbox_range
    fi
    reset_colors
    # prevlinepos should always be > 0 except on the initial call of draw_inbox()
    if (( prevlinepos > 0 )); then
	# Check if inbox_list_forward/backward wrapped around the list
	if (( prevlinepos == last_linepos && linepos == first_linepos )) ||\
	   (( prevlinepos == first_linepos && linepos == last_linepos )); then
	    reset_colors; set_cursor $prevlinepos 0; erase_line
	    if [[ "${marked_messages[@]}" =~ "${id_arr[prev_arr_index]}" ]]; then
		echo -e "$W*$R${header_arr[prev_index]}"
		reset_colors; erase_line
		echo -en " $Y${header_arr[prev_index+1]}"
	    else
		echo -e " $R${header_arr[prev_index]}"
		reset_colors; erase_line
		echo -en " $Y${header_arr[prev_index+1]}"
	    fi
	    reset_colors; set_cursor $linepos 0; erase_line
	    if [[ "${marked_messages[@]}" =~ "${id_arr[arr_index]}" ]]; then
		echo -e "$W*$R$Bbg$Bold${header_arr[index_at_cursor]}"
		reset_colors; erase_line
		echo -en " $Y$Bbg$Bold${header_arr[index_at_cursor+1]}"
	    else
		echo -e " $R$Bbg$Bold${header_arr[index_at_cursor]}"
		reset_colors; erase_line
		echo -en " $Y$Bbg$Bold${header_arr[index_at_cursor+1]}"
	    fi
	    reset_colors; set_cursor $linepos 0; return
	fi
	# Handle cursor going downward
	if (( prev_index < index_at_cursor )); then
	    set_cursor $prevlinepos 0; erase_line
	    if [[ "${marked_messages[@]}" =~ "${id_arr[prev_arr_index]}" ]]; then
		echo -e "$W*$R${header_arr[prev_index]}"
	    else echo -e " $R${header_arr[prev_index]}"; fi
	    reset_colors; erase_line; echo -e " $Y${header_arr[prev_index+1]}"
	    reset_colors; erase_line
	    if [[ "${marked_messages[@]}" =~ "${id_arr[arr_index]}" ]]; then
		echo -e "$W*$R$Bbg$Bold${header_arr[index_at_cursor]}"
	    else echo -e " $R$Bbg$Bold${header_arr[index_at_cursor]}"; fi
	    reset_colors; erase_line; echo -en " $Y$Bbg$Bold${header_arr[index_at_cursor+1]}"
	    reset_colors; set_cursor $linepos 0
	# Handle cursor going upward
	elif (( prev_index > index_at_cursor )); then
	    set_cursor $linepos 0; erase_line
	    if [[ "${marked_messages[@]}" =~ "${id_arr[arr_index]}" ]]; then
		echo -e "$W*$R$Bbg$Bold${header_arr[index_at_cursor]}"
	    else echo -e " $R$Bbg$Bold${header_arr[index_at_cursor]}"; fi
	    reset_colors; erase_line; echo -e " $Y$Bbg$Bold${header_arr[index_at_cursor+1]}"
	    reset_colors; erase_line
	    if [[ "${marked_messages[@]}" =~ "${id_arr[prev_arr_index]}" ]]; then
		echo -e "$W*$R${header_arr[prev_index]}"
	    else echo -e " $R${header_arr[prev_index]}"; fi
	    reset_colors; erase_line; echo -en " $Y${header_arr[prev_index+1]}"
	    reset_colors; set_cursor $linepos 0
	fi
    # Initial draw_inbox() call handler
    else
	arr_index=${arr_range[top]}
	set_cursor $linepos 0; reset_colors; erase_line
	if [[ "${marked_messages[@]}" =~ "${id_arr[arr_index]}" ]]; then
	    echo -e "$W*$R$Bbg$Bold${header_arr[index_at_cursor]}"
	else echo -e " $R$Bbg$Bold${header_arr[index_at_cursor]}"; fi
	reset_colors; erase_line; echo -en " $Y$Bbg$Bold${header_arr[index_at_cursor+1]}"
	reset_colors; set_cursor $linepos 0
    fi
}

##################################################################################
#				    NAVIGATION					 #
##################################################################################

function splash_forward_line() {
    (( linepos++ ))
    set_cursor $linepos $splashstart
}

function inbox_list_forward() {
    # Either 0 args, or flag "--unread"
    if [[ "$1" == "--unread" ]]; then
	local -n arr_range=unread_range
	local -n header_arr=unread_header_arr
	local -i count=$unreadcount
    elif [[ "$1" == "--inbox" ]]; then
	local -n arr_range=inbox_range
	local -n header_arr=inbox_header_arr
	local -i count=$inboxcount
    fi
    if (( count > 1 )); then
	linesum=$(( 2 + linepos ))
	# Wrap at last message if all messages are shown
	if (( linesum > last_linepos && count <= max_shown )); then
	    set_cursor $first_linepos 1
	    prevlinepos=$linepos
	    prev_index=$index_at_cursor
	    index_at_cursor=${arr_range[top]}
	    linepos=$first_linepos
	    highlight $1
	    update_bottom_bar $1
        # Only redraw bottom line when the last 2 indexes of
	# header_arr != arr_range[bottom]
	elif (( linesum >= bottomline && arr_range[bottom] < ${#header_arr[@]}-2 )); then
	    prevlinepos=$(( max_inbox_line - 2 ))
	    linepos=$max_inbox_line
	    (( arr_range[top]+=2 ))
	    (( arr_range[bottom]+=2 ))
	    prev_index=$index_at_cursor
	    (( index_at_cursor+=2 ))
	    highlight $1
	    update_bottom_bar $1
	elif (( index_at_cursor < arr_range[bottom] )); then
	    set_cursor $linesum 1
	    prevlinepos=$linepos
	    (( linepos += 2 ))
	    prev_index=$index_at_cursor
	    (( index_at_cursor+=2 ))
	    highlight $1
	    update_bottom_bar $1
	fi
    fi
}

function inbox_list_backward() {
     if [[ "$1" == "--unread" ]]; then
	local -n arr_range=unread_range
	local -i count=$unreadcount
    elif [[ "$1" == "--inbox" ]]; then
	local -n arr_range=inbox_range
	local -i count=$inboxcount
     fi
     if (( count > 1 )); then
	 linesum=$(( linepos - 2 ))
	 # Wrap at first message
	 if (( linesum < first_linepos && count <= max_shown )); then
	     set_cursor $max_inbox_line 1
	     prevlinepos=$linepos
	     linepos=$last_linepos
	     prev_index=$index_at_cursor
	     index_at_cursor=${arr_range[bottom]}
	     highlight $1
	     update_bottom_bar $1
	 elif (( linesum < first_linepos && arr_range[top] != 0 )); then
	     prevlinepos=$(( first_linepos + 2 ))
	     linepos=$first_linepos
	     (( arr_range[top]-=2 ))
	     (( arr_range[bottom]-=2 ))
	     prev_index=$index_at_cursor
	     (( index_at_cursor-=2 ))
	     highlight $1
	     update_bottom_bar $1
	 elif (( linesum >= first_linepos )); then
	     set_cursor $linesum 1
	     prevlinepos=$linepos
	     (( linepos -= 2 ))
	     prev_index=$index_at_cursor
	     (( index_at_cursor-=2 ))
	     highlight $1
	     update_bottom_bar $1
	 fi
     fi
}

function inbox_forward_page() {
    # Either 0 args, or flag "--unread"
    if [[ $# -eq 1 && "$1" == "--unread" ]]; then
	echo "ignore"
    fi
}

function unread_nav_mode() {
    while read -rsN 1 key; do
	case "$key" in
	    "")
		inbox_list_forward --unread
		;;
	    "")
		inbox_list_backward --unread
		;;
	    r)
		refresh_unread
		;;
	    j)
		inbox_list_forward --unread
		;;
	    k)
		inbox_list_backward --unread
		;;
	    m)
		mark_message
		;;
	    a)
		archive_marked_messages
		;;
	    d)
		delete_marked_messages
		;;
	    $'\n')
		draw_popup "Opening message"
		get_mime_structure --unread unread_msg_ids
		;;
	    $'\t')
		switch_to_inbox		
		;;
	    "")
		break
		;;
	    q)
		exit
		;;
	esac
    done
}

function inbox_nav_mode() {
    while read -rsN 1 key; do
	case "$key" in
	    "")
		inbox_list_forward --inbox
		;;
	    "")
		inbox_list_backward --inbox
		;;
	    j)
		inbox_list_forward --inbox
		;;
	    k)
		inbox_list_backward --inbox
		;;
	    m)
		mark_message
		;;
	    a)
		archive_marked_messages
		;;
	    d)
		delete_marked_messages
		;;
	    $'\n')
		draw_popup "Opening message"
		get_mime_structure --inbox inbox_msg_ids
		;;
	    $'\t')
		refresh_unread
		break
		;;
	    "")
		break
		;;
	    q)
		exit
		;;
	esac
    done
}

function message_nav_mode () {
    while read -rsN 1 key; do
	case "$key" in
	    $'\e')
		reset_indexes open_message
		draw_inbox "$1" --restore
		highlight "$1"
		break
		;;
	    q)
		reset_indexes open_message
		draw_inbox $1 --restore
		highlight $1
		break
		;;
	    b)
		draw_previous_page
		;;
	    f)
		draw_next_page
		;;
	    j)
		forward_line
		;;
	    k)
		backward_line
		;;
	    h)
		backward_column
		;;
	    l)
		forward_column
		;;
	    "")
		forward_column
		;;
	    "")
		backward_column
		;;
	    "")
		forward_line
		;;
	    "")
		backward_line
		;;
	esac
    done
}
#################################################################################
#			       MESSAGE PROCESSING				#
#################################################################################

function get_mime_structure() {
    # $1 --unread or --inbox
    # $2 $unread or $inbox_msg_ids
    clearfifo
    local -n id_arr=$2
    selected_message=${id_arr[$(rel_msg_index $index_at_cursor)]}
    local -A structure
    response=""; container=""; parens=""
    local -i paren_count
    structure[id]="$selected_message"
    structure[encoding]="none"
    echo "$A FETCH $selected_message BODYSTRUCTURE" >&$sendfd
    while read -r line; do
	if [[ "$line" =~ " OK " ]]; then break; fi
	if [[ "$line" =~ " BAD "|" NO " ]]; then
	    draw_popup --warn --restore-unread "Failed to get message structure"
	fi
	response+="$line"
    done <&$readfd
    # [1] is the parens. [2] is the format. [3] is the rest of the container.
    if [[ "$response" =~ BODYSTRUCTURE[^\(]*(\({1,})([^ ]{1,}" "[^ ]{1,})([^\)]*\)){2} ]]; then
	parens="${breg[1]}"
	structure[format]="${breg[2]}"
	container="${breg[*]:2:2}"
    fi
    [[ "$container" =~ Quoted-Printable|QUOTED-PRINTABLE ]] && structure[encoding]="qp"
    if (( ${#parens} > 0 )); then
	paren_count=$(( ${#parens}-1 ))
	(( paren_count == 3 )) && structure[leaf]="1.1.1"
	(( paren_count == 2 )) && structure[leaf]="1.1"
	(( paren_count == 1 )) && structure[leaf]="1"
    fi
    if [[ "${structure[format]}" =~ [Hh][Tt][Mm][Ll] ]]; then
	draw_popup --warn --restore-unread "HTML is not yet supported"
	return
    fi

    get_message $1 structure
}

function get_message() {
    # $1: --unread or --inbox
    # $2: AA structure
    local -n struct=$2
    local -i count=0
    echo "$A FETCH ${struct[id]} body.peek[${struct[leaf]}]" >&$sendfd
    read -r bytes <&$readfd
    [[ "$bytes" =~ \{([0-9]{1,})\} ]] && bytes="${breg[1]}"
    read -rN $bytes message <&$readfd
    while read -r line; do
	if [[ "$line" =~ " OK " ]]; then break; fi
	if [[ "$line" =~ " BAD "|" NO " ]]; then
	    draw_popup --warn --restore-unread "Failed to retrieve message"
	fi
    done <&$readfd
    while read -r line; do
	open_message[count]="$line"
	(( count++ ))
    done < <(echo "$message")
    if [[ "${struct[encoding]}" == "none" ]]; then
	parse_plain_links
	parse_html
	message_cleanup_whitespace
	print_message $1
    elif [[ "${struct[encoding]}" == "qp" ]]; then
	decode_qp --message
	parse_plain_links
	message_cleanup_whitespace
	print_message $1
    fi
}

# $1: namespace $2: index
function decode_b64() {
    local -n arr=$1
    full_string="${arr[$2]}"
    full_string="${full_string//$'\n'/}"
    [[ ! "$full_string" =~ \?= ]] && echo "End of Base64 not found"
    # Group 1: Plain text before first "=?"
    # Group 2: Base 64 encoded text found after "=?UTF-8?B?" and before "?="
    # Group 3: Any text after "?=" except if it starts with a space or "<"
    if [[ "$full_string" =~ ^[[:space:]]?([^=]*)=\?.{5}\?B\?([^\?]{1,})\?=([^\<[:space:]]*) ]]; then
	plain_pre="${breg[1]}"
	plain_post="${breg[3]}"
	encoded="${breg[2]//$'\n'/}"
	decoded=$(echo "$encoded"|base64 -d 2>/dev/null)
	if (( ${#plain_pre} > 0 )); then
	    if (( ${#plain_post} > 0 )); then
		echo "$plain_pre$decoded$plain_post"
	    else
		echo "$plain_pre$decoded"
	    fi
	else
	    echo "$decoded"
	fi
    fi
}

function decode_qp() {
    # $1: Flags. Either "--message" or "--header"
    # $2 is only used to provide either $from_arr or $subject_arr index
    clearfifo
    # Decode the whole messsage line by line
    if [[ "$1" == "--message" ]]; then
	for (( i=0;i<${#open_message[@]};i++ )); do
	    open_message[i]=$(echo "${open_message[$i]}"\
				   |sed -r 's/=([A-Za-z0-9]{2})/\\x\1/g;s/=//g')
	done
    # Header QP. $2 Passes in an index from an array
    elif [[ "$1" == "--header" ]]; then
	string="${2//$'\n'/}"
	[[ "$string" =~ ^" "?([^=]*) && ${#breg} -gt 0 ]] && string_pre_qp="$breg[1]"
	[[ "$string" =~ " "?[^=]*=\?.{5}\?Q\?(.*)\?= ]] && string_qp="${breg[1]//@(=\?UTF-8\?Q\?|\?=|$'\n')/}"
	if [[ -v string_qp && ${#string_qp} -gt 0 ]]; then
	    regex="=([A-Za-z0-9]{2})"
	    qp_message=$(echo "$string_qp"|sed -r "s/_/ /g; s/$regex/\\\x\1/g")
	    [[ -v string_pre_qp ]] && echo -e "$string_pre_qp$qp_message"\
		    || echo -e "$qp_message"
	else
	    echo "Failed to decode text"
	fi
    fi
}

function parse_html() {
    clearfifo
    for (( i=0;i<${#open_message[@]};i++ )); do
	open_message[i]=$(echo "${open_message[$i]}"\
			       |sed -r 's/<br>/\n/g; s/<\/?.*>//g')
    done
}

function parse_plain_links() {
    for (( i=0;i<${#open_message[@]};i++ )); do
	open_message[i]=$(echo "${open_message[$i]}"\
	  |sed -r "s/[(<]?.?(https?|mailto).*[)>[:blank:]]?/\\${BrB}Link\\$reset/g")
    done
}

function message_cleanup_whitespace() {
    # Any groups of 3 or more consecutive new lines, reduce to 2
    for (( i=0;i<${#open_message[@]};i++ )); do
	if [[ "${open_message[$i]}" =~ ^$'\n' &&\
		  "${open_message[$i+1]}" =~ ^$'\n' &&\
		  "${open_message[$i+2]}" =~ ^$'\n' ]]; then
	    unset "open_message[$i+2]"
	fi
    done
}

function print_message() {
    # $1 --unread or --inbox
    reset_colors
    reset_scroll_area
    clear
    for (( i=0;i<lines;i++ )); do
	if [[ -v open_message[$i] ]]; then
	    set_cursor $i 0
	    echo -en "${open_message[$i]}"
	    
	else
	    break
	fi
    done
    open_message_range[top]=0
    open_message_range[bottom]=$(( lines - 1 ))
    set_cursor 0 0
    message_line_pos=1
    mode="message"
    show_cursor
    message_nav_mode $1
}
#######################################################################
#			    Inbox/Unread Commands		      #
#######################################################################

function mark_message() {
    local -i index=$(rel_msg_index $index_at_cursor)
    if [[ "${marked_messages[@]}" =~ "${unread_msg_ids[index]}" ]]; then
	marked_index=$(get_index_n marked_messages "${unread_msg_ids[index]}")
	unset 'marked_messages[marked_index]'
	unmark_message
    else
	marked_messages+=("${unread_msg_ids[index]}")
	draw_marked_symbol
    fi
    local arr_str="${marked_messages[*]}"
    marked_str="${arr_str// /,}"
}

function draw_marked_symbol() {
    reset_colors
    echo -en "$W*"
    set_cursor $linepos 0
    reset_colors
}

function unmark_message() {
    reset_colors
    echo -n " "
    set_cursor $linepos 0
}

function archive_marked_messages() {
    draw_popup "Archiving selected messages"
    clearfifo
    echo "$A MOVE $marked_str ${folder[archived]}" >&$sendfd
    while read -r line; do
	if [[ "$line" =~ " OK " ]]; then break; fi
	if [[ "$line" =~ " BAD "|" NO " ]]; then
	    draw_popup --warn --restore-unread "Failed to archive messages"
	    return
	fi
    done <&$readfd
    reset_indexes marked_messages
    refresh_unread
}

function delete_marked_messages() {
    draw_popup "Deleting selected messages"
    clearfifo
    echo "$A MOVE $marked_str ${folder[trash]}" >&$sendfd
    while read -r line; do
	if [[ "$line" =~ .*Success.*|" OK " ]]; then break; fi
	if [[ "$line" =~ " BAD "|" NO " ]]; then
	    draw_popup --warn --restore-unread "Failed to delete messages"
	    return
	fi
    done <&$readfd
    reset_indexes marked_messages
    refresh_unread
}

function sort_array() {
    local -n arr=$1
    readarray -t sorted < <(printf '%s\n' "${arr[@]}"|sort -n)
    echo "${sorted[*]}"
}

#######################################################################
#			      Main init				      #
#######################################################################
# Remove terminal prompt
PS1=""

trap "echo -en '\e[?1049l'" EXIT ERR

# Get total columns and lines
read -r lines columns < <(stty size)

bottomline=$lines
max_shown=$(( (bottomline - 2) / 2 ))
max_inbox_line=$(( bottomline - 2 ))

termcenter=$(( columns / 2 ))
splashcenter=$(( splashlen / 2 ))
splashstart=$(( termcenter - splashcenter ))

clear
reset_colors

if (( splashlen < columns + 10 )); then
    for (( i=0; i<splashcols; i++ )); do
	set_cursor $(( linestart + i )) $splashstart
	echo -e "${splash[i]}"
	(( linepos++ ))
    done
    reset_colors
    splash_forward_line
fi

#################################################################################
#	       Get credentials -- Encrypt and store if not found		#
#################################################################################
bashmail_dir="${HOME}/.config/bashmail"
emailenc="$bashmail_dir/.emailenc"
passenc="$bashmail_dir/.passenc"
if ! test -d "$bashmail_dir"; then mkdir "$bashmail_dir"; fi

if ! [[ -f "$emailenc" && -f "$passenc"  ]]; then
    echo -n "Email: "
    read -r email
    echo "$email" | openssl aes-256-cbc -pbkdf2 -pass pass:"bashmailemail"\
    -out "$emailenc" >/dev/null # ~/.bashmail/.emailenc
    splash_forward_line

    echo -n "Pass: "
    read -s -r pass
    echo "$pass" | openssl aes-256-cbc -pbkdf2 -pass pass:"bashmailpass"\
    -out "$passenc" >/dev/null # ~/.bashmail/.passenc
    splash_forward_line
else
    echo "Found stored credentials. Decrypting..."
    email="$(openssl aes-256-cbc -pbkdf2 -d -pass pass:"bashmailemail" -in "$emailenc")"
    pass="$(openssl aes-256-cbc -pbkdf2 -d -pass pass:"bashmailpass" -in "$passenc")"
    splash_forward_line
fi

if [[ "$email" =~ "icloud.com" ]]; then
    imapdomain="imap.mail.me.com:993"
else
    imapdomain="$(echo 'imap.'$(echo $email | sed -e 's/^[^@]*@//')':993')"
fi


#################################################################################
#				    SSL Prep					#
#################################################################################
echo "Attempting to login..."
splash_forward_line

if ! [[ -p $sendssl ]]; then
    mkfifo /var/tmp/sendssl.log
fi

if ! [[ -p $readssl ]]; then
    mkfifo /var/tmp/readssl.log
fi

# Create FDs
exec {sendfd}<>/var/tmp/sendssl.log # use $sendfd -- Send commands here
exec {readfd}<>/var/tmp/readssl.log

#################################################################################
#				  Call openssl					#
#################################################################################
hide_mode
openssl s_client -connect "$imapdomain" -quiet -crlf <&$sendfd >&$readfd 2>/dev/null &
sslpid=$!

# Trap to kill ssl pid, restore previous terminal screen/coloring on term or error
trap "kill $sslpid; echo -en '\e[?1049l'; hide_mode_off; reset_colors" EXIT ERR

#################################################################################
#		       SSL connection and inbox selection			#
#################################################################################
while read -rs line; do
    case "$line" in
	"* OK"*) # Initial connection response
	    hide_mode_off
	    splash_forward_line
	    echo "SSL connection established. Sending credentials"
	    splash_forward_line
	    hide_mode
	    echo "$A LOGIN $email $pass" >&$sendfd
	    ;;
	"$A"*"OK"*$email*) # Response to $A LOGIN
	    hide_mode_off
	    echo "Successfully logged in"
	    unset pass
	    splash_forward_line
	    hide_mode
	    break
	    ;;
	*"BAD"*|*"NO"*) # Failed response of any kind
	    rm "$passenc" "$emailenc"
	    draw_popup --error "Failed to login"
	    ;;
	*)
	    continue
	    ;;
    esac
done <&$readfd

get_folders
get_unread_messages
fetch_header_field "$unread_str"
parse_headers --unread
combine_headers --unread unread_header_arr
clearfifo
hide_mode_off
draw_inbox --unread

##################################################################################
#				   BOTTOM BAR					 #
#			   Show cursor position range				 #
#				   Ex: (2/10)					 #
##################################################################################
bottom_text="" # Store globally to track the length between changes
set_bottom_bar --unread

# After bottom bar is set, rehighlight message at cursor
highlight --unread

unread_nav_mode

rm $sendssl $readssl
